# Generated by Django 2.0.1 on 2018-01-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_auditrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditrecord',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='auditrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuditRecord',
        ),
    ]
